apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
spec:
  replicas: 1
  selector:
    matchLabels: { app: web-service }
  template:
    metadata:
      labels: { app: web-service }
    spec:
      containers:
        - name: web-service
          image: YOUR_DOCKERHUB/micro-simple-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4000
          env:
            - name: AUTH_URL
              value: "http://auth-service:3000"
            - name: SESSION_SECRET
              value: "websecret"
            - name: PORT
              value: "4000"
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits: { cpu: "200m", memory: "256Mi" }
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector: { app: web-service }
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30081
  type: NodePort
