apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  labels:
    app: web-service
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: web-service
  template:
    metadata:
      labels: 
        app: web-service
    spec:
      containers:
        - name: web-service
          image: prakashbhati086/micro-simple-web:latest
          ports:
            - name: http
              containerPort: 4000
          env:
            - name: AUTH_URL
              value: "http://auth-service:3000"
            - name: SESSION_SECRET
              value: "websecret"
            - name: PORT
              value: "4000"
          readinessProbe:
            httpGet: 
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: 
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
