apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: prakashbhati086/microauthx-frontend-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:3000"
            - name: SESSION_SECRET
              value: "frontendsecret"
            - name: PORT
              value: "4000"
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
