apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: frontend-service
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
      tier: web
  template:
    metadata:
      labels:
        app: frontend-service
        tier: web
    spec:
      containers:
        - name: frontend-service
          image: prakashbhati086/microauthx-frontend-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4000
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:3000/api"
            - name: SESSION_SECRET
              value: "frontendsecret"
            - name: PORT
              value: "4000"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
    tier: web
spec:
  selector:
    app: frontend-service
    tier: web
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30080
  type: NodePort
