apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels: { app: auth-service }
  template:
    metadata:
      labels: { app: auth-service }
    spec:
      containers:
        - name: auth-service
          image: prakashbhati086/micro-simple-auth:latest
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: SESSION_SECRET
              value: "authsecret"
            - name: PORT
              value: "3000"
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017/simplemicro"
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits: { cpu: "500m", memory: "512Mi" }
