apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: auth-service
  template:
    metadata:
      labels: 
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: prakashbhati086/micro-simple-auth:latest
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017/simplemicro"
            - name: SESSION_SECRET
              value: "authsecret"
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet: 
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: 
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
