apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: bWljcm9hdXRobXg=   # base64 of 'microauthx'
  mongo-root-password: cGFzc3dvcmQxMjM=   # base64 of 'password123'
